# Generated by Django 3.1.3 on 2020-11-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201103_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='designer',
        ),
    ]
