# Generated by Django 3.1.3 on 2020-11-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201108_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='designer',
            new_name='user',
        ),
    ]
