# Generated by Django 3.1.3 on 2020-11-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiqueApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
