# Generated by Django 3.1.3 on 2020-11-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutiqueApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='designer',
        ),
    ]
