# Generated by Django 3.1.3 on 2020-11-10 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutiqueApp', '0002_designer_designername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='designer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boutiqueApp.designer'),
        ),
    ]
