# Generated by Django 3.1.3 on 2020-11-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiqueApp', '0005_auto_20201109_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='knot.jpeg', upload_to='market'),
        ),
    ]
